### ISSUE TITLE
why does it bring white to the edge of the picture?

### ISSUE THREAD

**Issue by damladalgic** [turner-anderson/streamlit-cropper#14]
<img width="515" alt="Screenshot 2022-12-21 194852" src="https://user-images.githubusercontent.com/119844523/208959727-32b0215f-af75-44c9-a6fb-e068cf5a576f.png">

**Comment by turner-anderson** [comment]
Could you see if this still happens on the version most recently pushed?

**Comment by fizahkhalid** [comment]
> Could you see if this still happens on the version most recently pushed?

Yes it done.

**Comment by turner-anderson** [comment]
Odd, I can't replicate the behavior. Could you give me a few more details on the environment and possibly how you're calling the cropper or whether you're using it in one of the streamlit container objects? You could try creating a new environment and pip installing streamlit-cropper, then copying app.py and seeing if that works as expected.

Here's my environment:

Windows 10
Python 3.11.1
Streamlit 1.16.0
streamlit-cropper 0.2.1
Chrome, Firefox and Edge browsers tested

**Comment by fizahkhalid** [comment]
Sure
Here's my environment:
Ubuntu (AWS EC2 Server)
Python 3.8.15
streamlit 1.16.0
streamlit-cropper  0.2.0  and 0.2.1 (both tested)
Chrome tested

This issue persisted in 2 different conda environments.

I believe image size has something to do with it. Most of the images I used only have this white area in "Wide Mode". 
The following image has it on both settings. 
WIDE MODE:
![image](https://user-images.githubusercontent.com/75387073/210500596-9bf79018-4bbd-49cb-841f-0c1f26105617.png)
 
WITHOUT WIDE MODE:
![image](https://user-images.githubusercontent.com/75387073/210500683-0b211b5a-f3ed-410b-9efa-8af3ef53989c.png)

**Comment by turner-anderson** [comment]
So from what I can tell this happens because Streamlit dynamically stretches the container that the image is in, it's especially noticeable if your computer/browser is in dark mode, because the canvas doesn't know to fill with black. I'm trying to figure out a way to force the component to not resize, but it may take some time.

**Comment by fizahkhalid** [comment]
Yes that is probably what's happening. I don't think theres any need to spend ample time on this. It is seamless in light mode. Thanks a lot for this library !

**Comment by turner-anderson** [comment]
Exciting news, I think I fixed it on the latest release.
