### ISSUE TITLE
Cropped coordinate as input

### ISSUE THREAD

**Issue by darwinharianto** [turner-anderson/streamlit-cropper#16]
Is it possible to input the coordinate of cropping box in the input?
So the cropping box starts at a predetermined coordinate

**Comment by turner-anderson** [comment]
Yes that should be possible, if you pass a function to the box_algorithm argument you can define any coordinate choosing method. By default it's just 60% of the original image, but if you wanted you could pass any arbitrary function. In advanced use cases I've seen people do something like object detection using YOLO as that recommended box and using that as a starting point.
