### ISSUE TITLE
get crop coordinate

### ISSUE THREAD

**Issue by Chop1** [turner-anderson/streamlit-cropper#2]
Is it possible to get the crop coordinate rather than the cropped image itself ?

**Comment by turner-anderson** [comment]
Yeah that shouldn't be hard at all. Let me do a little bit of research to see if it makes more sense semantically to add a "return_type" option to the function, or if it makes more sense to return both the image and the coordinates. I'll try to push something within the next few days.

**Comment by turner-anderson** [comment]
Alright, just pushed that update. There is now an argument called 'return_type' which if you set equal to 'box' will return a dictionary of the top, left, height, and width of the crop box. You should be able to get it with an upgrade to version 0.1.3.

Let me know if you have any issues.

**Comment by sibtain-raxa** [comment]
excellent work
