### ISSUE TITLE
Box width parameter could be updated

### ISSUE THREAD

**Issue by jeromemassot** [turner-anderson/streamlit-cropper#21]
Hi,
First, thank you for this util tool that perfectly integrated into Streamlit and fits my needs.
Kudos for that.

Change Request (additional feature): could it be possible to add a parameter for the box width the same as it exists for the box color?

I really appreciate any help you can provide.

Best regards

Jerome

**Comment by turner-anderson** [comment]
Done!

**Comment by jeromemassot** [comment]
Thanks a lot :)
