### ISSUE TITLE
return canvas data via on-demand button click or double tap

### ISSUE THREAD

**Issue by erjieyong** [turner-anderson/streamlit-cropper#23]
When realtime_update is False, the coordinates is only returned upon mouse double clicks. But this is not usable in a mobile environment. Would suggest 2 other alternative methods to return the coordinates.

1) Upon a streamlit button click
2) Upon double tapping on mobile device

**Comment by turner-anderson** [comment]
That should be doable, sorry for the long delay.

**Comment by turner-anderson** [comment]
On further investigation, this might be a lot harder than I anticipated, unless newer versions of fabric.js have better mobile support. On the most recent update, I updated the fabric version, could you install 0.2.2 and check whether this resolved the issue?

**Comment by erjieyong** [comment]
Hi @turner-anderson , thanks for reverting to me. I've managed to create my own version using cropperjs. 

[https://github.com/erjieyong/streamlit-cropperjs](https://github.com/erjieyong/streamlit-cropperjs )
