### ISSUE TITLE
Trouble loading streamlit_cropper.st_cropper component

### ISSUE THREAD

**Issue by shoebNTU** [turner-anderson/streamlit-cropper#3]
Hi,

Thanks for this helpful package. I am getting the following error - 

![error_streamlit_cropper](https://user-images.githubusercontent.com/27325112/119835975-ec157a80-bf33-11eb-821a-9bdb7274e5dd.png)

Could you please help me resolve it? Thanks.

**Comment by turner-anderson** [comment]
I'm having trouble replicating this error, can you give me your Python, streamlit, and streamlit-cropper versions? For reference, I tried with streamlit=0.82.0, streamlit-cropper=0.1.3, and python 3.8.5.
