### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by johnyquest7** [turner-anderson/streamlit-cropper#6]
Everything was working fine in the past. Now I am getting a new error from the following code. 

`import streamlit as st
from streamlit_cropper import st_cropper
from PIL import Image
st.set_option('deprecation.showfileUploaderEncoding', False)

# Upload an image and set some options for demo purposes
st.header("Cropper Demo")
img_file = st.sidebar.file_uploader(label='Upload a file', type=['png', 'jpg'])
realtime_update = st.sidebar.checkbox(label="Update in Real Time", value=True)
box_color = st.sidebar.color_picker(label="Box Color", value='#0000FF')
aspect_choice = st.sidebar.radio(label="Aspect Ratio", options=["1:1", "16:9", "4:3", "2:3", "Free"])
aspect_dict = {"1:1": (1,1),
                "16:9": (16,9),
                "4:3": (4,3),
                "2:3": (2,3),
                "Free": None}
aspect_ratio = aspect_dict[aspect_choice]

if img_file:
    img = Image.open(img_file)
    if not realtime_update:
        st.write("Double click to save crop")
    # Get a cropped image from the frontend
    cropped_img = st_cropper(img, realtime_update=realtime_update, box_color=box_color,
                                aspect_ratio=aspect_ratio)

    # Manipulate cropped image at will
    st.write("Preview")
    _ = cropped_img.thumbnail((150,150))
    st.image(cropped_img)
`

############################# see error below ##########
TypeError: string indices must be integers
Traceback:

File "/home/quest/anaconda3/envs/fastaiv2_2020_nov/lib/python3.8/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
File "/media/quest/extradrive1/fastaiv2_nov_2020/ThyroidReporter/cropp.py", line 24, in <module>
    cropped_img = st_cropper(img, realtime_update=realtime_update, box_color=box_color,
File "/home/quest/anaconda3/envs/fastaiv2_2020_nov/lib/python3.8/site-packages/streamlit_cropper/__init__.py", line 145, in st_cropper
    rect = component_value['coords']

**Comment by johnyquest7** [comment]
### Hacky fix
added following lines to cropper's init.py
import json
from contextlib import suppress

Changed line 145 to 162 as follows

`if component_value:
        tot = len(component_value) -1
        rect = component_value[10:tot]
    else:
        rect = box

   
   if return_type.lower() == 'image':
  
        with suppress(Exception):
            rect = json.loads(rect)
        cropped_img = img.crop((rect['left'], rect['top'], rect['width'] + rect['left'], rect['height'] + rect['top']))
        return cropped_img
    elif return_type.lower() == 'box':
        return rect`

**Comment by turner-anderson** [comment]
Hi Johnson, sorry for the long delay. I just pushed version 0.2.0. Let me know if you're still having similar issues on the newest version of Streamlit and streamlit-cropper. If so, I'll see what I can do to create a fix inside the package.

**Comment by okome-git** [comment]
@turner-anderson 
Could you explain how to build this app from scratch ?
I could build streamlit-drawable-canvas but not yours.

**Comment by turner-anderson** [comment]
@okome-git I created a new issue https://github.com/turner-anderson/streamlit-cropper/issues/10 to address your concern. I wanted to keep this clean for Johnson's unrelated issue.
