### ISSUE TITLE
component inside a button

### ISSUE THREAD

**Issue by mohbay** [turner-anderson/streamlit-cropper#8]
The component does not work properly if it goes inside a streamlit button and restarts.
Example code:
    if st.button("Proceed"):
        st.write("Double click to save crop")
        # st.write(aspect_ratio)
        # Get a cropped image from the frontend
        cropped_img = st_cropper(img, realtime_update=False,
                                    aspect_ratio=None)
        
        width, height = cropped_img.size
        # Manipulate cropped image at will
        st.write("Preview")
        _ = cropped_img.thumbnail((width, height))
        st.image(cropped_img)

**Comment by turner-anderson** [comment]
Hi mohbay. I think this may be more of a limitation of Streamlit rather than this particular component. For example, the following sample also exhibits similar behavior:

```
import streamlit as st

if st.button("Press me"):
    val = st.slider("Test slider", 0, 10, 5, 1)
    st.write(f"Value is {val}")
```
